var ccb_resources = [
    {type:'image', src:"ccbResources/images/btn_change_on.png"},
    {type:'ccbi', src:"ConnectToCustomClass.ccbi"},
    {type:'image', src:"ccbResources/images/main_menu_01.png"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/images/main_menu_04.png"},
    {type:'image', src:"ccbResources/images/btn_change_off.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"ccbResources/images/main_menu_02.png"},
    {type:'image', src:"clickme.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"ccbResources/images/main_menu_03.png"},
    {type:'image', src:"clickme-down.png"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
];
